config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "users/registrations", :sessions => "users/sessions"}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # devise_scope :user do
  #	 delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  # end

  resources :users do
    member do
      get :following_event, :following_local, :destroy
    end
  end

  resources :events do
    member do
      get :followers
      put "signal", to: "events#report"
    end
    resources :comments, except: [:index, :new, :show] do
      member do
        get :reply
        put "like", to: "comments#upvote"
        put "dislike", to: "comments#downvote"
        put "signal", to: "comments#report"
      end
    end
  end

  resources :locals do
    member do
      get :followers
      put "signal", to: "locals#report"
    end
    resources :comments, except: [:index, :new, :show] do
      member do
        get :reply
        put "like", to: "comments#upvote"
        put "dislike", to: "comments#downvote"
        put "signal", to: "comments#report"
      end
    end
  end

  resources :event_relationships, only: [:create, :destroy]
  resources :local_relationships, only: [:create, :destroy]
  #resources :comments, only: [:index, :create]
  resources :contacts, only: [:new, :create]

  root 'pages#home'
  
  get '/publish_events', to: 'owner_pages#publish_events'
  get '/publish_locals', to: 'owner_pages#publish_locals'
  get '/all_events', to: 'client_pages#all_events'
  get '/following', to: 'client_pages#following'
  get '/your_locals', to: 'owner_pages#your_locals'
  get '/your_events', to: 'owner_pages#your_events'
  get '/help',    to: 'pages#help'
  get '/notifications',    to: 'pages#notifications'
  get '/about',   to: 'pages#about'
  get '/contacts', to: 'contacts#new'
  get '/search',    to: 'pages#search'
  get '/banned', to: 'pages#banned'
  get '/events_all', to: 'admin_pages#events_all'
  get '/locals_all', to: 'admin_pages#locals_all'
  get '/users_all', to: 'admin_pages#users_all'
  post 'admin_pages/ban' => 'admin_pages#ban', :as => :ban
  post 'admin_pages/unban' => 'admin_pages#unban', :as => :unban
  post '/rate' => 'rater#create', :as => 'rate'

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :commentable, polymorphic: true
  belongs_to :parent, class_name: 'Comment', optional: true
  has_many :replies, class_name: 'Comment', foreign_key: :parent_id, dependent: :destroy

  validates :content, presence: true, length: { maximum: 400 }
  
  acts_as_votable
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_commentable
  before_action :set_comment, only: [ :reply, :edit, :update, :destroy ]
  before_action :correct_user, only: [:edit, :update ]
  before_action :correct_user_or_admin, only: [:destroy ]
 
  def reply
    @reply = @commentable.comments.build(parent: @comment)
  end
 
  def create
    @comment = @commentable.comments.build(comment_params)
    @comment.user = current_user
    #@comment.likes = 0
    
    #respond_to do |format|
      if @comment.save
        if @comment.commentable_type == 'Local' 
          if @comment.parent_id == nil
            if current_user != @commentable.user
              Notification.create(text: "Il tuo locale è stato commentato!", comment_id: @comment.id, additional_info: current_user.name, local_id: @comment.commentable_id, user_id: Local.find(@comment.commentable_id).user_id)
            end
            redirect_to local_path(@commentable, anchor: 'comment_' + @comment.id.to_s)
          else
            if (current_user != Comment.find(@comment.parent_id).user) && (current_user != Local.find(@comment.commentable_id).user)
              Notification.create(text: "Qualcuno ha risposto al tuo commento!", comment_id: @comment.id, additional_info: current_user.name, local_id: @comment.commentable_id, user_id: Comment.find(@comment.parent_id).user.id)
            elsif (current_user != Comment.find(@comment.parent_id).user) && (current_user == Local.find(@comment.commentable_id).user)
              Notification.create(text: "Qualcuno ha risposto al tuo commento!", comment_id: @comment.id, additional_info: Local.find(@comment.commentable_id).name, local_id: @comment.commentable_id, user_id: Comment.find(@comment.parent_id).user.id)
            end
            redirect_to local_path(@commentable, anchor: 'comment_' + @comment.parent_id.to_s)
          end 
        elsif @comment.commentable_type == 'Event' 
          if @comment.parent_id == nil
            if current_user != @commentable.local.user
              Notification.create(text: "Il tuo evento è stato commentato!", comment_id: @comment.id, additional_info: current_user.name, event_id: @comment.commentable_id, user_id: Event.find(@comment.commentable_id).local.user_id)
            end
            redirect_to event_path(@commentable, anchor: 'comment_' + @comment.id.to_s)
          else
            if (current_user != Comment.find(@comment.parent_id).user) && (current_user != Event.find(@comment.commentable_id).local.user)
              Notification.create(text: "Qualcuno ha risposto al tuo commento!", comment_id: @comment.id, additional_info: current_user.name, event_id: @comment.commentable_id, user_id: Comment.find(@comment.parent_id).user.id)
            elsif (current_user != Comment.find(@comment.parent_id).user) && (current_user == Event.find(@comment.commentable_id).local.user)
              Notification.create(text: "Qualcuno ha risposto al tuo commento!", comment_id: @comment.id, additional_info: Event.find(@comment.commentable_id).local.name, event_id: @comment.commentable_id, user_id: Comment.find(@comment.parent_id).user.id)
            end
            redirect_to event_path(@commentable, anchor: 'comment_' + @comment.parent_id.to_s)
          end
        end

        #format.html { redirect_to @commentable, notice: "Commento aggiunto."}
        #format.json { render json: @comment }
        #format.js
      else
        redirect_to @commentable, notice: "Commento non aggiunto. Riprova."
        #format.html { render :back, notice: "Commento non aggiunto. Riprova." }
        #format.json { render json: @comment.errors }
        #format.js
      end
    #end
  end
 
  def edit
  end
 
  def update
    if current_user == @comment.user
      respond_to do |format|
        if @comment.update(comment_params)
          format.html { redirect_to @commentable, notice: "Commento aggiornato."}
          format.json { render json: @comment }
          format.js
        else
          format.html { render :back, notice: "Commento non aggiornato. Riprova." }
          format.json { render json: @comment.errors }
          format.js
        end
      end
    else
      redirect_to @commentable
    end
  end
 
  def destroy
    if current_user == @comment.user
      if @comment.errors.empty?
        Notification.where(comment_id: @comment.id).destroy_all
        @comment.destroy 
        respond_to do |format|
          format.html { redirect_to @commentable, notice: "Commento eliminato."}
          format.json { head :no_content }
          format.js
        end
      end
    elsif current_user.role == 'admin' && current_user != @comment.user 
      if @comment.errors.empty?
        @text = @comment.content
        @receiver_id = @comment.user.id
        if @comment.commentable_type == 'Local' 
          @local_id = @comment.commentable_id
          Notification.where(text: "Il tuo locale è stato commentato!", local_id: @local_id, comment_id: @comment.id).destroy_all
          Notification.where(text: "Segnalazione locale!", event_id: @local_id).destroy_all
        else
          @event_id = @comment.commentable_id
            Notification.where(text: "Il tuo evento è stato commentato!", event_id: @event_id, comment_id: @comment.id).destroy_all
            Notification.where(text: "Segnalazione evento!", event_id: @event_id).destroy_all
        end
        @comment.destroy 

        Notification.create(text: "Commento eliminato da Admin!", additional_info: @text, user_id: @receiver_id)
         
        respond_to do |format|
          format.html { redirect_to @commentable, notice: "Commento eliminato."}
          format.json { head :no_content }
          format.js
        end
      end
    else
      redirect_to @commentable
    end
  end

  def upvote
    @comment = @commentable.comments.find(params[:id])
    @comment.liked_by current_user
    @comment.update_attributes(likes: @comment.likes + 1)
    respond_to do |format|
      format.html { redirect_to @commentable }
      format.json { render json: @comment }
      format.js
    end
  end

  def downvote
    @comment = @commentable.comments.find(params[:id])
    @comment.downvote_from current_user
    @comment.update_attributes(likes: @comment.likes - 1)
    respond_to do |format|
      format.html { redirect_to @commentable }
      format.json { render json: @comment }
      format.js
    end
  end

  def report
    @comment = @commentable.comments.find(params[:id])
    if @comment.commentable_type == 'Local' 
      Notification.create(text: "Segnalazione commento!", additional_info: current_user.name, comment_id: @comment.id, local_id: @comment.commentable_id, user_id: User.find_by(role: 'admin').id)
    elsif @comment.commentable_type == 'Event' 
      Notification.create(text: "Segnalazione commento!", additional_info: current_user.name, comment_id: @comment.id, event_id: @comment.commentable_id, user_id: User.find_by(role: 'admin').id)
    end
    respond_to do |format|
      format.html { redirect_to @commentable, notice: "Commento segnalato agli admin."}
      format.json { head :no_content }
      format.js
    end
  end
 
  private
 
  def set_commentable
    resource, id = request.path.split('/')[1,2]
    @commentable = resource.singularize.classify.constantize.find(id)
  end
 
  def set_comment
    begin
      @comment = @commentable.comments.find(params[:id])
    rescue => e
      logger.error "#{e.class.name} : #{e.message}"
      @comment = @commentable.comments.build
      @comment.errors.add(:base, :recordnotfound, message: "Commento inesistente o già eliminato.")
    end
  end
 
  def comment_params
    params.require(:comment).permit(:content, :parent_id)
  end

  def correct_user
    redirect_to(root_path) unless current_user == Comment.find(params[:id]).user 
  end

  def correct_user_or_admin
    redirect_to(root_path) unless current_user == Comment.find(params[:id]).user || current_user.role == 'admin'
  end
end

app/views/comments/_comment.html.erb
<li id="comment_<%= comment.id %>" class="comment">
  <% if user_signed_in? && comment.commentable_type=='Local' && comment.user == Local.find(comment.commentable_id).user %>
    <b><%= Local.find(comment.commentable_id).name %></b>
  <% elsif user_signed_in? && comment.commentable_type=='Event' && comment.user == Event.find(comment.commentable_id).local.user %>
    <b><%= Event.find(comment.commentable_id).local.name %></b>
  <% else %>
    <b><%= comment.user.name %></b>
  <% end %>
  <div class="comment-content">
    <%= comment.content %>
  </div>
  <div class="comment-info">
    <small>
      <% if user_signed_in? %>
        <% if current_user == comment.user %>
          <%= link_to "Modifica", edit_polymorphic_path([comment.commentable, comment]), class: 'edit-comment-link', remote: true  %> &bull;
          <%= link_to "Elimina", [comment.commentable, comment], method: :delete, class: 'delete-comment-link', data:{confirm:"Sei sicuro?"}, remote: true %> &bull;
        <% elsif current_user.role == 'admin' %>
          <%= link_to "Elimina", [comment.commentable, comment], method: :delete, class: 'delete-comment-link', data:{confirm:"Sei sicuro?"}, remote: true %> &bull;
        <% else %>
        <div style="display:none">
          <%= link_to "", edit_polymorphic_path([comment.commentable, comment]), class: 'edit-comment-link'  %> &bull;
          <%= link_to "", [comment.commentable, comment], class: 'delete-comment-link' %> &bull;
        </div>
        <% end %>
        <%= link_to "Rispondi", polymorphic_path([:reply, comment.commentable, comment]), class: 'reply-comment-link', remote: true  %> &bull;
      
        <% if comment.commentable_type == 'Local' %>

          <% if current_user.voted_up_on? comment %>
            <%= link_to "Non mi piace più", dislike_local_comment_path(comment.commentable.id, comment), method: :put, remote: true %>
          <% else %>
            <%= link_to "Mi piace", like_local_comment_path(comment.commentable.id, comment), method: :put, remote: true %>
          <% end %>

          <div style="float:right; color: #bbb;">
            <% if current_user.role == 'Cliente' && comment.user.role != 'admin' && current_user != comment.user%>
              <%= link_to "Segnala", signal_local_comment_path(comment.commentable.id, comment), method: :put, data:{confirm:"Sei sicuro?"} %>&bull; 
            <% end %>
            <%= localize(comment.updated_at, format: :long) %>
          </div>
        <% elsif comment.commentable_type == 'Event' %>

          <% if current_user.voted_up_on? comment %>
            <%= link_to "Non mi piace più", dislike_event_comment_path(comment.commentable.id, comment), method: :put, remote: true %>
          <% else %>
            <%= link_to "Mi piace", like_event_comment_path(comment.commentable.id, comment), method: :put, remote: true %>
          <% end %>

          <div style="float:right; color: #bbb;">
            <% if current_user.role == 'Cliente' && comment.user.role != 'admin' && current_user != comment.user%>
              <%= link_to "Segnala", signal_event_comment_path(comment.commentable.id, comment), method: :put, data:{confirm:"Sei sicuro?"} %>&bull; 
            <% end %>
            <%= localize(comment.created_at, format: :long) %>
          </div>
      <% end 
      end %>
      <% if comment.likes > 0 %>
        + <%= comment.likes %>
      <% end %>
    </small>
  </div>
  <% if comment.replies.any? %>
    <ul>
      <%= render comment.replies.order(:created_at) %>
    </ul>
  <% end %>
</li>

app/views/comments/_form.html.erb
<div class="comment-form">
  <%= form_for [comment.commentable, comment], remote: true do | f | %>
    <%= f.hidden_field :parent_id %>
    &nbsp;<%= link_to "Annulla", "#", 'data-reply': comment.parent_id.present?, class: 'cancel-comment-link' if comment.persisted? or comment.parent %>
    
    <div class="input-group">
		  <%= f.text_field :content, label: false, placeholder: (f.object.parent_id.nil? ? 'Commenta...' : 'Rispondi al commento...'), class: 'form-control' %>
		  <div class="input-group-btn">
		  	<%= f.submit "Invia", class: 'btn btn-in' %>
		  </div>
		</div>
    <div class="clearfix"></div>
  <% end %>
</div>

app/views/comments/_widget.html.erb
<h4>Commenti: &nbsp;
  <small id="comments-count-of-commentable-<%= commentable.id %>">
    <% if commentable.comments.size > 1 %>
      (<%= commentable.comments.size %> commenti)
    <% elsif commentable.comments.size == 1%>
      (1 commento)
    <% else %>
      (nessun commento)
    <% end %>
  </small>
</h4>

<div id="comments-widget-of-commentable-<%= commentable.id %>" class="comments-widget">
  <!-- comment-form -->
  <% if user_signed_in? %>
    <%= render "comments/form", comment: commentable.comments.build %>
    <% if commentable.comments.size > 1 %><br><% end %>
  <% end %>

  <ul class="comments-list">
    <% if user_signed_in? %>
      <%= render commentable.comments.where({parent: nil, user_id: current_user.id}).order(created_at: :desc) %>
      <%= render commentable.comments.where(parent: nil).where.not(user_id: current_user.id).order(likes: :desc, created_at: :desc) %>
    <% else %>
      <br>
      <%= render commentable.comments.where(parent: nil).order(likes: :desc, created_at: :desc) %>
    <% end %>
  </ul>
</div>

app/views/comments/create.js.erb
// create.js.erb (CommentsController#create)
<% if @comment.parent %>
  $comment_parent = $("#comment_<%= @comment.parent.id %> > ul");
  if(!$comment_parent.length){
    $("#comment_<%= @comment.parent.id %>").append("<ul></ul>");
    $comment_parent = $("#comment_<%= @comment.parent.id %> > ul");
  }
  $comment_form = $("#comment_<%= @comment.parent.id %> .comment-form form");
<% else %>
  $comment_parent = $("#comments-widget-of-commentable-<%= @commentable.id %> .comments-list");
  $comment_form = $("#comments-widget-of-commentable-<%= @commentable.id %> .comment-form form");
<% end %>
$comments_count = $("#comments-count-of-commentable-<%= @commentable.id %>");
<% if @comment.errors.empty?  # if no erros on creating a comment... %>
  $comments_count.html("<%= @commentable.comments.size %>");//.effect('highlight',{}, 1000);
  $comment_parent.append("<%=j render @comment %>");//.find('li').last().effect("highlight", {}, 1000);
  $comment_form[0].reset();
  <% if @comment.parent %>
    $comment_form.remove();
    // console.log("start");
    $comment = $("#comment_<%= @comment.parent.id %>")
    // console.log("end");
    $restore_link = $comment.find('a.delete-comment-link')[0]
    $reply_link = $comment.find('a.reply-comment-link')[0]
    $reply_link.href = $restore_link.href + "/reply"
  <% end %>
  $("#comment_new_chars_counter").html("Remaining : 255");
<% else # if some errors occurs on creating a comment... %>
  $comment_form.before("<div class='alert alert-warning alert-dismissible fade in' role='alert'><button type='button' class='close' data-dismiss='alert' aria-label='Close'><span aria-hidden='true'>&times;</span></button><%= @comment.errors.full_messages.join('') %></div>").prev().delay(1500).slideUp();
<% end %>

app/views/comments/destroy.js.erb
$comments_count = $("#comments-count-of-commentable-<%= @commentable.id %>");
<% if @comment.errors.empty? %>
  $comments_count.html("<%= @commentable.comments.size %>").effect('highlight',{}, 1000);
  $("#comment_<%= @comment.id %>").slideUp('fast');//.effect("highlight", { color: '#f7937c' }, 500).slideUp('fast');
<% else %>
  $("#comments-widget-of-commentable-<%= @commentable.id %> .comments-header").after("<div class='alert alert-warning alert-dismissible fade in' role='alert'><button type='button' class='close' data-dismiss='alert' aria-label='Close'><span aria-hidden='true'>&times;</span></button><%= @comment.errors.full_messages.join('') %></div>").next().delay(1500).slideUp('fast');
<% end %>

app/views/comments/downvote.js.erb
// upvote.js.erb (CommentsController#upvote)
$(document).ready(function(){
  $('#comment_<%= @comment.id %>').html("<%=j render @comment %>");
});

app/views/comments/edit.js.erb
// edit.js.erb
<% if @comment.errors.empty? %>
  $("#comment_<%= @comment.id %> > .comment-info .edit-comment-link").removeAttr("href");
  $("#comment_<%= @comment.id %> > .comment-info").after("<%=j render('comments/form', comment: @comment) %>");
<% else %>
  $("#comments-widget-of-commentable-<%= @commentable.id %> .comments-header").after("<div class='alert alert-warning alert-dismissible fade in' role='alert'><button type='button' class='close' data-dismiss='alert' aria-label='Close'><span aria-hidden='true'>&times;</span></button><%= @comment.errors.full_messages.join('') %></div>").next().delay(1500).slideUp('fast');
<% end %>

// On editing a comment, call to counter of comment.
$("#comment_<%= @comment.id %> form textarea").trigger('keyup');

app/views/comments/reply.js.erb
// reply.js.erb
<% if @comment.errors.empty? %>
  $("#comment_<%= @comment.id %> > .comment-info .reply-comment-link").removeAttr("href");
  $("#comment_<%= @comment.id %> > .comment-info").after("<%=j render('comments/form', comment: @reply) %>");
<% else %>
  $("#comments-widget-of-commentable-<%= @commentable.id %> .comments-header").after("<div class='alert alert-warning alert-dismissible fade in' role='alert'><button type='button' class='close' data-dismiss='alert' aria-label='Close'><span aria-hidden='true'>&times;</span></button><%= @comment.errors.full_messages.join('') %></div>").next().delay(1500).slideUp('fast');
<% end %>

app/views/comments/update.js.erb
// update.js.erb (CommentsController#create)
$comment_form = $("#comment_<%= @comment.id %> .comment-form form");
$comment = $("#comment_<%= @comment.id %>");
<% if @comment.errors.empty?  # if no erros on creating a comment... %>
  $comment.html("<%=j render @comment %>");//.find('li').last().effect("highlight", {}, 1000);
  $comment_form[0].remove();
<% else # if some errors occurs on creating a comment... %>
  $comment_form.before("<div class='alert alert-warning alert-dismissible fade in' role='alert'><button type='button' class='close' data-dismiss='alert' aria-label='Close'><span aria-hidden='true'>&times;</span></button><%= @comment.errors.full_messages.join('') %></div>").prev().delay(1500).slideUp();
<% end %>

app/views/comments/upvote.js.erb
// upvote.js.erb (CommentsController#upvote)
$(document).ready(function(){
  $('#comment_<%= @comment.id %>').html("<%=j render @comment %>");
});