config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "users/registrations", :sessions => "users/sessions"}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # devise_scope :user do
  #	 delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  # end

  resources :users do
    member do
      get :following_event, :following_local, :destroy
    end
  end

  resources :events do
    member do
      get :followers
      put "signal", to: "events#report"
    end
    resources :comments, except: [:index, :new, :show] do
      member do
        get :reply
        put "like", to: "comments#upvote"
        put "dislike", to: "comments#downvote"
        put "signal", to: "comments#report"
      end
    end
  end

  resources :locals do
    member do
      get :followers
      put "signal", to: "locals#report"
    end
    resources :comments, except: [:index, :new, :show] do
      member do
        get :reply
        put "like", to: "comments#upvote"
        put "dislike", to: "comments#downvote"
        put "signal", to: "comments#report"
      end
    end
  end

  resources :event_relationships, only: [:create, :destroy]
  resources :local_relationships, only: [:create, :destroy]
  #resources :comments, only: [:index, :create]
  resources :contacts, only: [:new, :create]

  root 'pages#home'
  
  get '/publish_events', to: 'owner_pages#publish_events'
  get '/publish_locals', to: 'owner_pages#publish_locals'
  get '/all_events', to: 'client_pages#all_events'
  get '/following', to: 'client_pages#following'
  get '/your_locals', to: 'owner_pages#your_locals'
  get '/your_events', to: 'owner_pages#your_events'
  get '/help',    to: 'pages#help'
  get '/notifications',    to: 'pages#notifications'
  get '/about',   to: 'pages#about'
  get '/contacts', to: 'contacts#new'
  get '/search',    to: 'pages#search'
  get '/banned', to: 'pages#banned'
  get '/events_all', to: 'admin_pages#events_all'
  get '/locals_all', to: 'admin_pages#locals_all'
  get '/users_all', to: 'admin_pages#users_all'
  post 'admin_pages/ban' => 'admin_pages#ban', :as => :ban
  post 'admin_pages/unban' => 'admin_pages#unban', :as => :unban
  post '/rate' => 'rater#create', :as => 'rate'

end

app/models/notification.rb
class Notification < ApplicationRecord
	belongs_to :user
	belongs_to :event, optional: true
	belongs_to :local, optional: true
	belongs_to :comment, optional: true
	
	default_scope -> { order(created_at: :desc) }

	validates :user_id, presence: true
  	validates :text, presence: true, length: { maximum: 1900 }

end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_notification.html.erb
<li id="notification-<%= notification.id %>">
  <div class="row">
    <div class="col-sm-12">
      <% if (notification.text == "Evento scaduto!") %>
        <%= notification.text %>
        <p>Il tuo evento "<b><%= notification.additional_info %></b>" è stato eliminato perchè scaduto</p>
		  
      <% elsif (notification.text == "Nuovo evento!") %>
        <%= notification.text %>
        	<p>Ciao! Il locale "<b><%= link_to notification.local.name, notification.local %></b>" che stai seguendo ha appena pubblicato un nuovo evento: <%= link_to notification.event.name, notification.event %></p>
      
      <% elsif (notification.text == "Evento seguito scaduto!") %>
        <%= notification.text %>
        <p>L'evento "<b><%= notification.additional_info %></b>" seguito in precedenza è scaduto!</p>
      
      <% elsif (notification.text == "Evento in avvicinamento!") %>
        <%= notification.text %>
        <% if !notification.event.blank? %>
        <p>L'evento "<b><%= link_to notification.event.name, notification.event %></b>" si terrà alle <b><%=notification.event.start.strftime("ore %H:%M del %d-%m-%y") %></b></p>
        <% end %>
      
      <% elsif (notification.text == "Evento eliminato da Admin!") %>
        <%= notification.text %>
        <p>Il tuo evento "<b><%= notification.additional_info %></b>" è stato eliminato dall'Admin</p>
      
      <% elsif (notification.text == "Locale eliminato da Admin!") %>
        <%= notification.text %>
        <p>Il tuo locale "<b><%= notification.additional_info %></b>" è stato eliminato dall'Admin</p>

      <% elsif (notification.text == "Commento eliminato da Admin!") %>
        <%= notification.text %>
        <p>Il tuo commento "<b><%= truncate(notification.additional_info, :length => 20) %></b>" è stato eliminato dall'Admin</p>
      
      <% elsif (notification.text == "Il tuo locale è stato commentato!") %> 
        <%= notification.text %>
        <% if notification.local != nil %>
        <p><b><%= notification.additional_info %></b> ha aggiunto un <%= link_to "commento", local_path(notification.local, anchor: "comment_" + notification.comment_id.to_s)%> al tuo locale "<b><%= link_to notification.local.name, notification.local %></b>": <%= truncate(notification.comment.content, :length => 20) %> ...</p>
        <% else %>
          <p><b><%= notification.additional_info %></b> ha aggiunto un commento al tuo locale.</p>
        <% end %>
      
      <% elsif (notification.text == "Il tuo evento è stato commentato!") %> 
        <%= notification.text %>
        <% if notification.event != nil %>
        <p><b><%= notification.additional_info %></b> ha aggiunto un <%= link_to "commento", event_path(notification.event, anchor: "comment_" + notification.comment_id.to_s)%> al tuo evento "<b><%= link_to notification.event.name, notification.event %></b>": <%= truncate(notification.comment.content, :length => 20) %> ...</p>
        <% else %>
          <p><b><%= notification.additional_info %></b> ha aggiunto un commento al tuo evento.</p>
        <% end %>

      <% elsif (notification.text == "Qualcuno ha risposto al tuo commento!") %>
        <%= notification.text %>
        <% if notification.event != nil && notification.local == nil %>
          <p><b><%= notification.additional_info %></b> ha risposto al tuo <%= link_to "commento", event_path(notification.event, anchor: "comment_" + notification.comment_id.to_s)%> sull'evento <b><%= link_to notification.event.name, notification.event %></b>": <%= truncate(notification.comment.content, :length => 20) %>...</p>
        <% elsif notification.local != nil && notification.event == nil %>
          <p><b><%= notification.additional_info %></b> ha risposto al tuo <%= link_to "commento", local_path(notification.local, anchor: "comment_" + notification.comment_id.to_s)%> sul locale <b><%= link_to notification.local.name, notification.local %></b>": <%= truncate(notification.comment.content, :length => 20) %> ...</p>
        <% end %>

      <% elsif (notification.text == "Segnalazione locale!") %> 
        <%= notification.text %>
        <p><b><%= notification.additional_info %></b> ha segnalato un locale: "<b><%= link_to notification.local.name, notification.local %></b>"</p>

      <% elsif (notification.text == "Segnalazione evento!") %> 
        <%= notification.text %>
        <p><b><%= notification.additional_info %></b> ha segnalato un evento: "<b><%= link_to notification.event.name, notification.event %></b>"</p>

      <% elsif (notification.text == "Segnalazione commento!") %> 
        <%= notification.text %>
        <% if notification.event != nil && notification.local == nil %>
          <p><b><%= notification.additional_info %></b> ha segnalato un <%= link_to "commento", event_path(notification.event, anchor: "comment_" + notification.comment_id.to_s)%> sull'evento <b><%= link_to notification.event.name, notification.event %></b>": <%= truncate(notification.comment.content, :length => 20) %>...</p>
        <% elsif notification.local != nil && notification.event == nil %>
          <p><b><%= notification.additional_info %></b> ha segnalato un <%= link_to "commento", local_path(notification.local, anchor: "comment_" + notification.comment_id.to_s)%> sul locale <b><%= link_to notification.local.name, notification.local %></b>": <%= truncate(notification.comment.content, :length => 20) %> ...</p>
        <% end %>

      <% elsif (notification.text == "Evento locale seguito eliminato!") %>
        <%= notification.text %>
        <p>Ciao! L'evento "<b><%= notification.additional_info %></b>" è stato eliminato in seguito all'eliminazione del locale!</p>

      <% elsif (notification.text == "Locale seguito eliminato!") %>
        <%= notification.text %>
        <p>Il locale "<b><%= notification.additional_info %></b>" seguito in precedenza è stato eliminato!</p>

        <% elsif (notification.text == "Evento in avvicinamento eliminato!") %>
        <%= notification.text %>
        <p>L'evento "<b><%= notification.additional_info %></b>" in avvicinamento è stato eliminato!</p>

      <% elsif (notification.text == "Evento seguito eliminato!") %>
        <%= notification.text %>
        <p>L'evento "<b><%= notification.additional_info %></b>" seguito in precedenza è stato eliminato!</p>

      <% end %> 
    </div>
  </div>
</li>