config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "users/registrations", :sessions => "users/sessions"}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # devise_scope :user do
  #	 delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  # end

  resources :users do
    member do
      get :following_event, :following_local, :destroy
    end
  end

  resources :events do
    member do
      get :followers
      put "signal", to: "events#report"
    end
    resources :comments, except: [:index, :new, :show] do
      member do
        get :reply
        put "like", to: "comments#upvote"
        put "dislike", to: "comments#downvote"
        put "signal", to: "comments#report"
      end
    end
  end

  resources :locals do
    member do
      get :followers
      put "signal", to: "locals#report"
    end
    resources :comments, except: [:index, :new, :show] do
      member do
        get :reply
        put "like", to: "comments#upvote"
        put "dislike", to: "comments#downvote"
        put "signal", to: "comments#report"
      end
    end
  end

  resources :event_relationships, only: [:create, :destroy]
  resources :local_relationships, only: [:create, :destroy]
  #resources :comments, only: [:index, :create]
  resources :contacts, only: [:new, :create]

  root 'pages#home'
  
  get '/publish_events', to: 'owner_pages#publish_events'
  get '/publish_locals', to: 'owner_pages#publish_locals'
  get '/all_events', to: 'client_pages#all_events'
  get '/following', to: 'client_pages#following'
  get '/your_locals', to: 'owner_pages#your_locals'
  get '/your_events', to: 'owner_pages#your_events'
  get '/help',    to: 'pages#help'
  get '/notifications',    to: 'pages#notifications'
  get '/about',   to: 'pages#about'
  get '/contacts', to: 'contacts#new'
  get '/search',    to: 'pages#search'
  get '/banned', to: 'pages#banned'
  get '/events_all', to: 'admin_pages#events_all'
  get '/locals_all', to: 'admin_pages#locals_all'
  get '/users_all', to: 'admin_pages#users_all'
  post 'admin_pages/ban' => 'admin_pages#ban', :as => :ban
  post 'admin_pages/unban' => 'admin_pages#unban', :as => :unban
  post '/rate' => 'rater#create', :as => 'rate'

end

app/controllers/owner_pages_controller.rb
class OwnerPagesController < ApplicationController
	before_action :authenticate_user!
  before_action :check_role

  def publish_events
  	@event = Event.new
  end

  def publish_locals
  	@local = current_user.locals.build
  end

  def your_events
  end

  def your_locals
  end

  private

  def check_role
    if not current_user.role == 'Gestore'
      if current_user.role == 'Cliente'
        redirect_to all_events_path
      elsif current_user.role == 'admin'
        redirect_to events_all_path
      elsif current_user.role == 'banned'
        redirect_to banned_path
      else
        redirect_to root_path
      end
    end
  end
  
end

app/helpers/owner_pages_helper.rb
module OwnerPagesHelper
end

app/views/owner_pages/publish_events.html.erb
<%= provide(:title,'Pubblica Evento') %>

<h1>Pubblica evento</h1><br>

<% if current_user.locals.empty? %>
  <center><h3>Non hai ancora inserito un locale</h3>
  <h2>Prima di poter creare un evento devi aggiungere un locale <%= link_to "qui", publish_locals_path %></h2></center>
<% else %>

  <div class="row">
    <div class="col-md-6 col-md-offset-3">
        
      	<%= form_for @event do |f| %>
          <%= render 'shared/error_messages', object: f.object %>
          <%= f.label :Locale %><br />
      		<%= f.select :local_id, options_for_select(Local.find_by_sql(["SELECT * FROM locals WHERE user_id = ? ", current_user.id]).collect{|p| [ p.name,p.id] }), {:id => "select_local"} %>  <!-- value:id, option:name -->
    			<div class="field">
            <%= f.label :Nome %><br />
      			<%= f.text_field :name, placeholder: "Inserisci nome", class: "form-control" %>
    			</div>

          <div class="field">
            <%= f.label :Inizio %><br />
            <%= f.text_field :start, placeholder: "Inserisci data e ora di inizio evento", class: 'datetimepicker12 form-control' %>
          </div>

          <div class="field">
            <%= f.label :Fine %><br />
            <%= f.text_field :end, placeholder: "Inserisci data e ora di fine evento", class: 'datetimepicker12 form-control' %>
          </div>
    			
    			<div class="field">
            <%= f.label :Descrizione %><br />
      			<%= f.text_area :description, placeholder: "Inserisci descrizione", class: "form-control" %>
    			</div>
    			<span class="picture">
            <p>Inserisci un'immagine per l'evento:</p>
      			<%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
    			</span>
    			<%= f.submit "Pubblica", class: "btn btn-primary" %>
          <% end %>
          <br><br>
          <%= link_to 'Annulla', :back %>
  	  
    </div>
  </div>
        
  <script type="text/javascript">
    $('#local_picture').bind('change', function() {
      var size_in_megabytes = this.files[0].size/1024/1024;
      if (size_in_megabytes > 5) {
        alert('Maximum file size is 5MB. Please choose a smaller file.');
      }
    });

    $(function () {
      $('.datetimepicker12').datetimepicker({
        sideBySide: true,
        format: 'HH:mm D-MM-YYYY',
        minDate: moment(),
        locale: moment.locale('it')
      });
    });
  </script>
<% end %>

app/views/owner_pages/publish_locals.html.erb
<%= provide(:title,'Pubblica Locale') %>

<h1>Pubblica locale</h1><br>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
	  <div class="local_form">
    	<%= form_for(@local) do |f| %>
    		<%= render 'shared/error_messages', object: f.object %>
  			<div class="field">
          <%= f.label :Nome %><br />
    			<%= f.text_field :name, placeholder: "Inserisci nome", class: "form-control" %>
  			</div>
        <div class="field">
          <%= f.label :Categoria %><br />
          <%= f.select(:category, ['Pub', 'Ristorante', 'Dance']) %>
        </div>
  			<div class="field" id="address" name="address" tag="address">
          <%= f.label :Indirizzo %><br />
    			<%= f.text_field :address, placeholder: "Inserisci indirizzo", id: "loc-address", class: "form-control" %>
  			</div>
        <div class="field">
          <%= f.label :Telefono %><br />
          <%= f.text_field :telephone, placeholder: "Inserisci telefono", class: "form-control" %>
        </div>
        <div class="field">
          <%= f.label :Sito_web %>&nbsp;&nbsp;<small>(attenzione al formato: es. 'www.nightsout.it')</small><br>
          <%= f.text_field :website, placeholder: "Inserisci sito internet", class: "form-control" %>
        </div>
        <div class="field">
          <%= f.label :Partita_IVA %><br />
          <%= f.text_field :iva, placeholder: "Inserisci partita iva", class: "form-control" %>
        </div>
  			<div class="field">
          <%= f.label :Descrizione %><br />
    			<%= f.text_area :description, placeholder: "Inserisci descrizione", class: "form-control" %>
  			</div>
        
  			<span class="picture">
          <p>Inserisci un'immagine per l'evento:</p>
    			<%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
  			</span>
  			<%= f.submit "Pubblica", class: "btn btn-primary" %>
		  <% end %>
      <br><br>
      <%= link_to 'Annulla', :back %>
	  </div>
  </div>
</div>

<script src = "https://maps.googleapis.com/maps/api/js?key=AIzaSyAXXF9Al_dOIDzdjzBcd5vgF8RtcWNE8_Y&libraries=places&callback=initializeAddr" async defer>
</script>
    
<script>
  var options = {
    types: ['address'],
    componentRestrictions: {country: "it"}
  };

  function initializeAddr() {
    var input = document.getElementById("loc-address");
    new google.maps.places.Autocomplete(input, options);
  }
</script>

<script type="text/javascript">
  $('#local_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>

app/views/owner_pages/your_events.html.erb
<%= provide(:title, 'I tuoi eventi') %>
<br><h1>I tuoi eventi</h1><br>

<div class="row">
  <div class="col-md-10 col-md-offset-1">
  <p>Aggiungi un nuovo evento:&nbsp;&nbsp;&nbsp;<%= link_to "Aggiungi evento", publish_events_path, class: "btn btn-primary" %></p>
  <br>

    <% current_user.locals.each do |l| 
        @cont=0
        if l.events.any?
          @cont += l.events.count 
    			@events = l.events.paginate(page: params[:page], :per_page => 5) %>
          <h3>Eventi in <%= l.name %>: (<%= @cont %>)</h3>
          <ol class="events">
            <%= render @events %>
          </ol>
          <%= will_paginate @events %>
    		<% end
    	 end 
    	 %>
  </div>
</div>

app/views/owner_pages/your_locals.html.erb
<%= provide(:title, 'I tuoi locali') %>
<br><h1>I tuoi locali</h1><br>

<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <p>Aggiungi un nuovo locale:&nbsp;&nbsp;&nbsp;<%= link_to "Aggiungi locale", publish_locals_path, class: "btn btn-primary" %></p>
  <br>
    <% if current_user.locals.any? %>
      <% @locals = current_user.locals.paginate(page: params[:page], :per_page => 5) %>
      <h3>Locali (<%= current_user.locals.count %>)</h3><br>
      <ol class="locals">
        <%= render @locals %>
      </ol>
      <%= will_paginate @locals %>
    <% end %>
    
  </div>
</div>