config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "users/registrations", :sessions => "users/sessions"}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # devise_scope :user do
  #	 delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  # end

  resources :users do
    member do
      get :following_event, :following_local, :destroy
    end
  end

  resources :events do
    member do
      get :followers
      put "signal", to: "events#report"
    end
    resources :comments, except: [:index, :new, :show] do
      member do
        get :reply
        put "like", to: "comments#upvote"
        put "dislike", to: "comments#downvote"
        put "signal", to: "comments#report"
      end
    end
  end

  resources :locals do
    member do
      get :followers
      put "signal", to: "locals#report"
    end
    resources :comments, except: [:index, :new, :show] do
      member do
        get :reply
        put "like", to: "comments#upvote"
        put "dislike", to: "comments#downvote"
        put "signal", to: "comments#report"
      end
    end
  end

  resources :event_relationships, only: [:create, :destroy]
  resources :local_relationships, only: [:create, :destroy]
  #resources :comments, only: [:index, :create]
  resources :contacts, only: [:new, :create]

  root 'pages#home'
  
  get '/publish_events', to: 'owner_pages#publish_events'
  get '/publish_locals', to: 'owner_pages#publish_locals'
  get '/all_events', to: 'client_pages#all_events'
  get '/following', to: 'client_pages#following'
  get '/your_locals', to: 'owner_pages#your_locals'
  get '/your_events', to: 'owner_pages#your_events'
  get '/help',    to: 'pages#help'
  get '/notifications',    to: 'pages#notifications'
  get '/about',   to: 'pages#about'
  get '/contacts', to: 'contacts#new'
  get '/search',    to: 'pages#search'
  get '/banned', to: 'pages#banned'
  get '/events_all', to: 'admin_pages#events_all'
  get '/locals_all', to: 'admin_pages#locals_all'
  get '/users_all', to: 'admin_pages#users_all'
  post 'admin_pages/ban' => 'admin_pages#ban', :as => :ban
  post 'admin_pages/unban' => 'admin_pages#unban', :as => :unban
  post '/rate' => 'rater#create', :as => 'rate'

end

app/views/layouts/_footer.html.erb
<br><br><br><br><br>
<!--<footer class="footer">
  <div class="row">
    <div class="col-xs-1"></div>
    <div class="col-xs-6">
  <br>
  <small>
    Footer del sito, cose varie contatti vari copyright non lo so solite cose da footer
  </small>
</div>
<div class="col-xs-4">
  <br>
  <nav>
    <ul>
      <li><%= link_to "FAQ", help_path %></li>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contacts", contacts_path %></li>
    </ul>
  </nav>
</div>
<div class="col-xs-1"></div>
</footer>-->

<footer class="footer">
  <div class="container">
    <div class="row">
      <div class="col-sm-2 col-xs-12">
        <br>
        <center><img src="/assets/icon.png" style="width:80%;max-width:150px;"></center><br>
      </div>
      <div class="col-sm-2 col-xs-3 footer-col">
        <br>
        <nav>
          <ul>
            <li style="color: #b4cbe4"><b>&bull;&nbsp;AIUTO</b></li><br>
            <li><%= link_to "FAQ", help_path %></li> 
          </ul>
        </nav>
      </div>
      <div class="col-sm-2 col-xs-3 footer-col">
        <br>
        <nav>
          <ul>
            <li style="color: #b4cbe4"><b>&bull;&nbsp;INFO</b></li><br>
            <li><%= link_to "About", about_path %></li> 
          </ul>
        </nav>
      </div>
      <div class="col-sm-3 col-xs-6 footer-col">
        <br>
        <nav>
          <ul>
            <li style="color: #b4cbe4"><b>&bull;&nbsp;CONTATTI</b></li><br>
            <li>nightsoutstaff@gmail.com</li>
            <li>pagina facebook</li>
            <li><%= link_to "Contacts", contacts_path %></li>  
          </ul>
        </nav>
      </div>
      
      <div class="col-sm-3 col-xs-12 footer-col">
        <br><br><br><center>Nightsout copiright trademark ecc</center><br>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-static-top navbar-inverse">
  <div class="container">
    <nav>
      <!--<img src="assets/nightsout_scritta.png" style="width:90px; padding:5px; left:0px">-->
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <% if current_user.role == 'Cliente' %>
            <li><%= link_to "Home", all_events_path %></li>
            <li><%= link_to "Cerca", search_path %></li>
            <li><%= link_to "Seguiti", following_path %></li>
            <li><%= link_to "Notifiche (" + Notification.where(['user_id = ? AND read = ?', current_user.id, false]).count.to_s + ")", notifications_path %></li>
            <li><%= link_to "Impostazioni", edit_user_registration_path %></li>
            <li><%= link_to "Esci", destroy_user_session_path, method: :delete %></li>
          <% elsif current_user.role == 'Gestore' %>
            <li><%= link_to "Tuoi eventi", your_events_path %></li>
            <li><%= link_to "Tuoi locali", your_locals_path %></li>
            <li><%= link_to "Notifiche (" + Notification.where(['user_id = ? AND read = ?', current_user.id, false]).count.to_s + ")", notifications_path %></li>
            <li><%= link_to "Impostazioni", edit_user_registration_path %></li>
            <li><%= link_to "Esci", destroy_user_session_path, method: :delete %></li>
          <% elsif current_user.role == 'admin' %>
            <li><%= link_to "Tutti gli eventi", events_all_path %></li>
            <li><%= link_to "Tutti i locali", locals_all_path %></li>
            <li><%= link_to "Tutti gli utenti", users_all_path %></li>
            <li><%= link_to "Notifiche (" + Notification.where(['user_id = ? AND read = ?', current_user.id, false]).count.to_s + ")", notifications_path %></li>
            <li><%= link_to "Esci", destroy_user_session_path, method: :delete %></li>
          <% elsif current_user.role == 'banned' %>
            <li><%= link_to "Esci", destroy_user_session_path, method: :delete %></li>
          <% end %>
        <% else %>
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Cerca", search_path %></li>
          <li><%= link_to "Accedi", new_user_session_path %></li>
          <li><%= link_to "Registrati", new_user_registration_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header> 
<div class="container">
  <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>
</div>
<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Nightsout</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

  </head>

  <body>
  	<% @title = yield(:title) %>
  	<%if @title != 'Home' %>
  		<%= render 'layouts/header'%>
  		<div class="container" style="min-height: 600px;">
  			<%= yield %>
      </div>
    		<%= render 'layouts/footer' %>
  	<% else %>
  		<%= yield %>
    		<%= render 'layouts/footer' %>
  	<% end %>

  </body>
  
  <%= javascript_include_tag 'jquery.raty', 'data-turbolinks-track': false %>
  <%= javascript_include_tag 'ratyrate', 'data-turbolinks-track': false %>
 
</html>